In [6]:
import numpy as np

In [7]:

# Array Creation:
 # Create a 1-dimensional array of integers from 1 to 10.
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# Create a 2-dimensional array with random float values of shape (3, 4).
arr_1=np.array
d=np.random.rand(3,4) #create an array of random value
d

array([[0.31456132, 0.15860168, 0.976411  , 0.13035163],
       [0.9825156 , 0.09713677, 0.39083947, 0.15514063],
       [0.81223016, 0.41159795, 0.2150608 , 0.4946292 ]])

In [14]:
# Create a 3-dimensional array of zeros with shape (2, 3, 4).
arr_2=np.array
d=np.zeros((2,3,4))
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
# Array Operations:
# Given two 1-dimensional arrays, perform element-wise addition,subtraction, multiplication, and division.
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
c

array([5, 7, 9])

In [16]:
d=a-b
d

array([-3, -3, -3])

In [18]:
e=a*b
e

array([ 4, 10, 18])

In [19]:
f=a/b
f

array([0.25, 0.4 , 0.5 ])

In [25]:
# Calculate the mean, median, and standard deviation of a given 1-dimensional array.
x=np.array([1,2,3,4,5])
mean_a = np.mean(x)
mean_a

3.0

In [24]:
median_a=np.median(x)
median_a

3.0

In [27]:
std_a=np.std(x)
std_a

1.4142135623730951

In [28]:
# Reshape a 1-dimensional array into a 2-dimensional array of shape (3,4).
res=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshaped_arr=res.reshape(3,4)
print("reshaped Array:",reshaped_arr)

reshaped Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [34]:
# Array Indexing and Slicing:
# Extract the first row and last column of a 2-dimensional array.
last_first = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
first_row = last_first[0, :]
last_col = last_first[:, -1]
print(f"First Row: {first_row}")
print(f"Last Column: {last_col}")

First Row: [1 2 3]
Last Column: [3 6 9]


In [38]:
# Reverse the order of elements in a 1-dimensional array.
rev_arr=np.array([1,2,3,4])
rev_sort=rev_arr[-1::-1]
rev_sort

array([4, 3, 2, 1])

In [40]:
# Select elements from a 2-dimensional array that satisfy a specific condition (e.g., values greater than a certain threshold).
import numpy as np

# Define a properly shaped 2D array
d_arr = np.array([[2, 4, 6, 8], [10, 12, 14, 16], [18, 20, 22, 24]])
threshold = 5
elements = d_arr[d_arr > threshold]
print("Elements greater than threshold:", elements)

Elements greater than threshold: [ 6  8 10 12 14 16 18 20 22 24]


In [41]:
# Array Broadcasting:
# Add a scalar value to each element of a 2-dimensional array.
broad=np.array([[1,2,3,4],[5,6,7,8]])
scalar=8
cast=broad+scalar
cast

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [43]:
# Multiply a 1-dimensional array with a 2-dimensional array, leveraging NumPy's broadcasting rules.
matr=np.array([[2,4,6,8],[10,12,14,16]])
vect=np.array([2,2,2,2])
multi=matr*vect
multi

array([[ 4,  8, 12, 16],
       [20, 24, 28, 32]])

In [44]:
# Linear Algebra:
# Calculate the dot product of two 1-dimensional arrays.
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
dot_product=np.dot(arr1,arr2)
dot_product

70

In [48]:
# Compute the matrix multiplication of two 2-dimensional arrays.
x=np.array([[1,2,4],[3,4,10]])
y=np.array([[12,13,14],[16,17,18],[19,20,21]])
multi=np.dot(x,y)
print("Matrix Multiplication:",multi)

Matrix Multiplication: [[120 127 134]
 [290 307 324]]


In [49]:
# Find the inverse and determinant of a square matrix.
import numpy as np
A = np.array([[4, 7], [2, 6]])
determinant = np.linalg.det(A)
if determinant != 0:
    inverse = np.linalg.inv(A)
    print("Determinant:", determinant)
    print("Inverse:\n", inverse)
else:
    print("Matrix is singular, inverse does not exist.")

Determinant: 10.000000000000002
Inverse:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
