### Import Libraries


In [38]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import seaborn as sns
import matplotlib.pyplot as plt

### Load Dataset

In [3]:
data_value=pd.read_csv("Hospital_Repository.csv")

### Check the data

In [4]:
x=data_value.drop("Geographic aggregation",axis=1)
y=data_value["Geographic aggregation"]

In [5]:
x=pd.get_dummies(x,drop_first=True)

In [6]:
data_value.index

RangeIndex(start=0, stop=12768, step=1)

In [8]:
# data_value.columns

In [15]:
data_value.info #to view null values

<bound method DataFrame.info of       Week Ending Date Geographic aggregation  Number of Inpatient Beds  \
0            8/12/2023                     WA                   10650.0   
1            8/12/2023                     WI                   10752.0   
2            8/12/2023                     WV                    4813.0   
3            8/12/2023                     WY                    1318.0   
4            8/19/2023                     AK                    1354.0   
...                ...                    ...                       ...   
12763        8/12/2023                    USA                  681406.0   
12764        8/12/2023                     UT                    5764.0   
12765        8/12/2023                     VA                   16500.0   
12766        8/12/2023                     VI                     168.0   
12767        8/12/2023                     VT                    1171.0   

       Number of Adult Inpatient Beds  Number of Pediatric Inpatien

In [17]:
data_value.dtypes

Week Ending Date                                                                                                             object
Geographic aggregation                                                                                                       object
Number of Inpatient Beds                                                                                                    float64
Number of Adult Inpatient Beds                                                                                              float64
Number of Pediatric Inpatient beds                                                                                          float64
                                                                                                                             ...   
Absolute Change in the Percent Hospitals Reporting Percent Inpatient Beds Occupied by Influenza Patients from Prior Week    float64
Absolute Change in the Percent Hospitals Reporting Percent Inpatient Beds Oc

In [9]:
# data_value.describe()

In [10]:
# data_value['Geographic aggregation'].unique

<bound method Series.unique of 0         WA
1         WI
2         WV
3         WY
4         AK
        ... 
12763    USA
12764     UT
12765     VA
12766     VI
12767     VT
Name: Geographic aggregation, Length: 12768, dtype: object>

In [11]:
# data_value['Number of Pediatric Inpatient beds'].value_counts()

In [12]:
# data_value.isna().sum()

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33, random_state = 42)

In [14]:
print(x_train)
print(y_train)
print(x_test)
print(y_test)

       Number of Inpatient Beds  Number of Adult Inpatient Beds  \
5871                    12607.0                         10876.0   
12656                    4818.0                          4563.0   
5903                     8040.0                          5757.0   
4924                     8154.0                          7503.0   
7822                     2840.0                          2293.0   
...                         ...                             ...   
11964                   51495.0                         48085.0   
5191                     1474.0                          1291.0   
5390                     7904.0                          5638.0   
860                     12518.0                         11603.0   
7270                       75.0                            60.0   

       Number of Pediatric Inpatient beds  Number of Inpatient Beds Occupied  \
5871                               1731.0                             8583.0   
12656                              

In [15]:
from sklearn.tree import DecisionTreeClassifier


In [16]:
classifier=DecisionTreeClassifier()

In [17]:
classifier.fit(x_train,y_train)

DecisionTreeClassifier()

In [19]:
# # instamtiates the decisionTreeClassifier model with criterion gini index
clf_gini=DecisionTreeClassifier(criterion='gini',max_depth=3,random_state=0)
# # fit
clf_gini.fit(x_train,y_train)


DecisionTreeClassifier(max_depth=3, random_state=0)

In [20]:
y_pred_gini=clf_gini.predict(x_test)

In [21]:
from sklearn.metrics import accuracy_score

print('Model accuracy score with criterion gini index: {0:0.4f}'. format(accuracy_score(y_test, y_pred_gini)))

Model accuracy score with criterion gini index: 0.0752


In [22]:
y_pred_train_gini=clf_gini.predict(x_train)
y_pred_train_gini

array(['NH', 'NH', 'NH', ..., 'NH', 'NH', 'MP'], dtype=object)

In [23]:
print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train_gini)))

Training-set accuracy score: 0.0897


In [25]:
# print the scores on training and test set

print('Training set score: {:.4f}'.format(clf_gini.score(x_train, y_train)))

print('Test set score: {:.4f}'.format(clf_gini.score(x_test, y_test)))

Training set score: 0.0897
Test set score: 0.0752


In [27]:
# instantiate the DecisionTreeClassifier model with criterion entropy

clf_en = DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=0)


# fit the model
clf_en.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=0)

In [29]:
y_pred_en = clf_en.predict(x_test)

In [30]:
from sklearn.metrics import accuracy_score

print('Model accuracy score with criterion entropy: {0:0.4f}'. format(accuracy_score(y_test, y_pred_en)))

Model accuracy score with criterion entropy: 0.1220


In [32]:
y_pred_train_en = clf_en.predict(x_train)

y_pred_train_en

array(['WA', 'OR', 'IA', ..., 'IA', 'IA', 'MP'], dtype=object)

In [33]:
print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train_en)))

Training-set accuracy score: 0.1420


In [35]:
# print the scores on training and test set

print('Training set score: {:.4f}'.format(clf_en.score(x_train, y_train)))

print('Test set score: {:.4f}'.format(clf_en.score(x_test, y_test)))

Training set score: 0.1420
Test set score: 0.1220


In [40]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_en)

print('Confusion matrix\n\n', cm)


Confusion matrix

 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [39]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_en))

              precision    recall  f1-score   support

          AK       0.00      0.00      0.00        70
          AL       0.00      0.00      0.00        82
          AR       0.00      0.00      0.00        76
          AS       0.00      0.00      0.00        71
          AZ       0.00      0.00      0.00        77
          CA       0.00      0.00      0.00        82
          CO       0.00      0.00      0.00        83
          CT       0.00      0.00      0.00        79
          DC       0.00      0.00      0.00        74
          DE       0.00      0.00      0.00        60
          FL       0.00      0.00      0.00        60
          GA       0.00      0.00      0.00        80
          GU       0.00      0.00      0.00        72
          HI       0.00      0.00      0.00        88
          IA       0.08      0.89      0.15        65
          ID       0.00      0.00      0.00        81
          IL       0.00      0.00      0.00        80
          IN       0.00    

C:\Users\aayus\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aayus\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aayus\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
